-- Law Agent MVP Database Setup
-- Run this SQL in your Supabase SQL Editor

-- 1. Create a table for Legal Documents (The "Brain")
CREATE TABLE IF NOT EXISTS legal_docs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    metadata JSONB NOT NULL,
    -- For MVP, we use simple text search instead of vectors
    search_vector TSVECTOR GENERATED ALWAYS AS (to_tsvector('english', content)) STORED
);

-- Create index for text search
CREATE INDEX IF NOT EXISTS legal_docs_search_idx ON legal_docs USING GIN (search_vector);

-- 2. Create a table for Lawyers (The "Business")
CREATE TABLE IF NOT EXISTS lawyers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    specialty TEXT NOT NULL,
    location TEXT NOT NULL,
    rate TEXT NOT NULL
);

-- 3. Insert MOCK DATA (Tenancy Scenario)
INSERT INTO legal_docs (content, metadata) VALUES
(
    'A landlord must not increase the rent payable under a residential rental agreement at intervals of less than 12 months.',
    '{"source": "Residential Tenancies Act 1997 (Vic)", "section": "s 44(4A)", "url": "http://austlii.edu.au/..."}'
),
(
    'A landlord must give the tenant at least 60 days notice of a proposed rent increase.',
    '{"source": "Residential Tenancies Act 1997 (Vic)", "section": "s 44(1)", "url": "http://austlii.edu.au/..."}'
);

-- 4. Insert MOCK LAWYERS
INSERT INTO lawyers (name, specialty, location, rate) VALUES
('Sarah Jenkins', 'Tenancy', 'Melbourne', '$300/hr'),
('James Li', 'Commercial', 'Sydney', '$450/hr'),
('Maria K.', 'Family Law', 'Melbourne', '$350/hr');
